// import BookImage from './assets/image/image_book.jpg';

// export const data = [
//   {
//     image: '',
//     title: 'Грокаем алгоритмы. Иллюстрированное пособие для программистов и любопытствующих',
//     author: 'Адитья Бхаргава',
//     year: 2019,
//     free: true,
//     returnDate: '',
//     grade: 0,
//     id: 1,
//     bookImages: [],
//   },
//   {
//     image: `${BookImage}`,
//     title: 'Грокаем алгоритмы. Иллюстрированное ',
//     author: 'Адитья Бхаргава',
//     year: 2019,
//     free: true,
//     returnDate: '',
//     grade: 4,
//     id: 2,
//     bookImages: [BookImage],
//   },
//   {
//     image: `${BookImage}`,
//     title: 'Грокаем алгоритмы.',
//     author: 'Адитья Бхаргава',
//     year: 2019,
//     free: false,
//     returnDate: '03.05',
//     grade: 4,
//     id: 3,
//     bookImages: [BookImage,BookImage,BookImage,BookImage,BookImage],
//   },
//   {
//     image: `${BookImage}`,
//     title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
//     author: 'Адитья Бхаргава',
//     year: 2019,
//     free: true,
//     returnDate: '',
//     grade: 4,
//     id: 4,
//     bookImages: [],
//   },
//   {
//     image: `${BookImage}`,
//     title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
//     author: 'Адитья Бхаргава, Патрик Нимейер',
//     year: 2019,
//     free: false,
//     returnDate: '',
//     grade: 4,
//     id: 5,
//     bookImages: [],
//   },
//   {
//     image: '',
//     title: 'Грокаем алгоритмы. Иллюстрированное ',
//     author: 'Адитья Бхаргава, Патрик Нимейер',
//     year: 2019,
//     free: false,
//     returnDate: '03.05',
//     grade: 4,
//     id: 6,
//     bookImages: [],
//   },
//   {
//     image: `${BookImage}`,
//     title: 'Грокаем алгоритмы. ',
//     author: 'Адитья Бхаргава, Патрик Нимейер',
//     year: 2019,
//     free: true,
//     returnDate: '',
//     grade: 4,
//     id: 7,
//     bookImages: [],
//   },
//   {
//     image: `${BookImage}`,
//     title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
//     author: 'Адитья Бхаргава, Патрик Нимейер',
//     year: 2019,
//     free: true,
//     returnDate: '',
//     grade: 4,
//     id: 8,
//     bookImages: [],
//   },
//   {
//     image: '',
//     title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
//     author: 'Адитья Бхаргава',
//     year: 2019,
//     free: false,
//     returnDate: '03.05',
//     grade: 4,
//     id: 9,
//     bookImages: [],
//   },
// ];

export const links = [
  {
    title: 'Витрина книг',
    active: true,
    link: '/',
    id: 1,
    testId: 'navigation-showcase',
    testIdBoorger: 'burger-showcase',
    sectionsBooks: [
      {
        subSectionsBooks: 'Все книги',
        count: null,
        active: true,
        subLink: 'all',
        testId: 'navigation-books',
        testIdBoorger: 'burger-books',
      },
      {
        subSectionsBooks: 'Бизнес-книги',
        count: 14,
        active: false,
        subLink: 'business',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Детективы',
        count: 8,
        active: false,
        subLink: 'detective',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Детские книги',
        count: 14,
        active: false,
        subLink: 'children',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Зарубежная литература',
        count: 2,
        active: false,
        subLink: 'foreign',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'История',
        count: 5,
        active: false,
        subLink: 'history',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Классическая литература',
        count: 12,
        active: false,
        subLink: 'classic',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Книги по психологии',
        count: 11,
        active: false,
        subLink: 'psyhology',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Компьютерная литература',
        count: 54,
        active: false,
        subLink: 'computer',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Культура и искусство',
        count: 5,
        active: false,
        subLink: 'culture',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Наука и образование',
        count: 2,
        active: false,
        subLink: 'science',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Публицистическая литература ',
        count: 0,
        active: false,
        subLink: 'journalistic',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Справочники',
        count: 10,
        active: false,
        subLink: 'reference',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Фантастика',
        count: 2,
        active: false,
        subLink: 'fantasy',
        testId: null,
        testIdBoorger: '',
      },
      {
        subSectionsBooks: 'Юмористическая литература',
        count: 0,
        active: false,
        subLink: 'humor',
        testId: null,
        testIdBoorger: '',
      },
    ],
  },
  {
    title: 'Правила пользования',
    active: false,
    link: '/rules',
    id: 2,
    testId: 'navigation-terms',
    testIdBoorger: 'burger-terms',
    sectionsBooks: [],
  },
  {
    title: 'Договор оферты',
    active: false,
    link: '/contract',
    id: 3,
    testId: 'navigation-contract',
    testIdBoorger: 'burger-contract',
    sectionsBooks: [],
  },
];
